[package]
name = "treeizsh-module"
version.workspace = true
edition.workspace = true
description = "Zsh module wrapping the treeizsh syntax highlighter"
license.workspace = true
repository.workspace = true
readme.workspace = true

[lib]
name = "treeizsh"
crate-type = ["cdylib"]

[dependencies]
treeizsh.workspace = true
oxizsh.workspace = true
oxizsh-module.workspace = true
toml.workspace = true
serde.workspace = true

[build-dependencies]
oxizsh-build.workspace = true

[dev-dependencies]
oxizsh-test.workspace = true

[[test]]
name = "zsh_tests"
path = "tests/zsh_tests.rs"
harness = false
