[package]
name = "zsh-tree-sitter-highlighter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
libc = "0.2"
rayon = "1"
tree-sitter = "0.26.8"
tree-sitter-highlight = "0.26.8"
tree-sitter-md = { version = "0.5.3", features = ["parser"] }
tree-sitter-zsh = "0.63.3"

[dev-dependencies]
googletest = "0.14.2"
insta = "1"
tempfile = "3"
