[package]
name = "tests"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
expectrl.workspace = true
regex.workspace = true
tempfile.workspace = true
zsh-module-test.workspace = true

[dev-dependencies]
treeish-module.workspace = true

[[test]]
name = "tautology"
path = "tautology.rs"

[[test]]
name = "zle"
path = "zle.rs"

[[bin]]
name = "debug_zle"
path = "src/bin/debug_zle.rs"
