"command.invalid" = "red"
"comment" = { fg = "overlay2", modifiers = ["italic"] }
"constant" = "peach"
"embedded" = "peach"
"function" = "blue"
"keyword" = "mauve"
"number" = "peach"
"operator" = "sky"
"path" = { modifiers = ["underline"] }
"path.directory" = { fg = "blue", modifiers = ["underline"] }
"property" = "blue"
"punctuation.delimiter" = "overlay2"
"punctuation.special" = "blue"
"string" = "green"
"string.escape" = "pink"
"text.emphasis" = { fg = "red", modifiers = ["italic"] }
"text.literal" = "green"
"text.reference" = "lavender"
"text.strong" = { fg = "red", modifiers = ["bold"] }
"text.title" = "red"
"text.uri" = { fg = "blue", modifiers = ["italic", "underlined"] }
"variable" = "text"

[palette]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
cursorline = "#2a2b3c"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
secondary_cursor = "#b5a6a8"
secondary_cursor_insert = "#7ea87f"
secondary_cursor_normal = "#b5a6a8"
secondary_cursor_select = "#878ec0"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"
