comment = "light_gray"
constant = "red"
embedded = "teal"
function = "blue"
keyword = "purple"
number = "orange"
operator = "cyan"
property = "teal"
string = "yellow"
"text.emphasis" = "purple"
"text.literal" = "yellow"
"text.reference" = "blue"
"text.strong" = "purple"
"text.title" = "blue"
"text.uri" = "teal"
"punctuation.delimiter" = "cyan"
"punctuation.special" = "cyan"
"string.escape" = "red"
variable = "magenta"
"command.invalid" = { fg = "red", modifiers = ["bold"] }
"path" = "underline"
"path.directory" = { fg = "blue", modifiers = ["underline"] }

[palette]
light_gray = "#565f89"
red = "#ff5370"
teal = "#73daca"
blue = "#7aa2f7"
purple = "#c099ff"
orange = "#ff9e64"
cyan = "#89ddff"
yellow = "#e0af68"
magenta = "#bb9af7"
