[package]
name = "treeish-module"
version.workspace = true
edition.workspace = true

[lib]
name = "treeish"
crate-type = ["cdylib"]

[dependencies]
treeish.workspace = true
zsh-module.workspace = true
toml.workspace = true
serde.workspace = true

[build-dependencies]
zsh-module-build.workspace = true

[dev-dependencies]
zsh-module-test.workspace = true

[[test]]
name = "zsh_tests"
path = "tests/zsh_tests.rs"
harness = false
