[package]
name = "treeish-module"
version = "0.1.0"
edition = "2024"

[lib]
name = "treeish"
crate-type = ["cdylib"]

[dependencies]
treeish = { path = "../treeish" }
zsh-module = { path = "/Users/nilton/Code/zsh-module-worktree/main/zsh-module" } #, git = "https://github.com/NiltonVolpato/zsh-module.git" }
toml = "1.1"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
zsh-module-build = { path = "/Users/nilton/Code/zsh-module-worktree/main/zsh-module-build" }

[dev-dependencies]
zsh-module-test = { path = "/Users/nilton/Code/zsh-module-worktree/main/zsh-module-test" }

[[test]]
name = "zsh_tests"
path = "tests/zsh_tests.rs"
harness = false
