[package]
name = "treeish"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
anyhow.workspace = true
libc.workspace = true
rayon.workspace = true
serde.workspace = true
serde_derive.workspace = true
tree-sitter.workspace = true
tree-sitter-highlight.workspace = true
tree-sitter-md.workspace = true
tree-sitter-zsh.workspace = true

[dev-dependencies]
googletest.workspace = true
tempfile.workspace = true

